analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.808103
  rhythmicContrast: 0.532072
  saturation: 1
cta: {}
layout_spectrum: 0.0626
name: b-minus party
opengraph: {}
purpose: []
typography_spectrum: 0.14476
